spring.application.name=forohub
spring.datasource.url=jdbc:mysql://localhost/"colocar nombre base de datos"
spring.datasource.username="colocar usuario DB"
spring.datasource.password="colocar password base de datos"

spring.jpa.show-sql= true
spring.jpa.properties.hibernate.format_sql=true

api.security.secret = "colocar password de login"
